### ISSUE TITLE
issue for walletbusy

### ISSUE THREAD

**Issue by zarrrsa** [busy-technology/BusyDesktopWallet#2]
keep loading after screate wallet , is there the same problem with me ?
![photo_2022-04-05_23-25-19](https://user-images.githubusercontent.com/80745120/161801357-be236d3f-4171-46c1-92cd-4bb7d5ea6601.jpg)

**Comment by busy-technology** [comment]
Hello,
Busy Testnet has been under DDoS fire 🔫 for the last three hours, and the attack is still ongoing. We have been forced to terminate Busy API to block the attacker. BusyChain is not affected; nothing happened to the network itself. We are pausing testing of the desktop wallet until further notice. We are honoured to be under the fire already on the testnet. That means that Busy is well awaited. Thank you for your feedback! 🚀
Twitter👉 https://bit.ly/3r5lwqu
