### ISSUE TITLE
cant generate passphrase

### ISSUE THREAD

**Issue by mr1407** [busy-technology/BusyDesktopWallet#3]
why i cant get to next for passphrase??

**Comment by busy-technology** [comment]
Hello,
Busy Testnet has been under DDoS fire 🔫 for the last three hours, and the attack is still ongoing. We have been forced to terminate Busy API to block the attacker. BusyChain is not affected; nothing happened to the network itself. We are pausing testing of the desktop wallet until further notice. We are honoured to be under the fire already on the testnet. That means that Busy is well awaited. Thank you for your feedback! 🚀
Twitter👉 https://bit.ly/3r5lwqu

**Comment by mr1407** [comment]
and the solution we all just waiting for further information from your team??until when??
