### ISSUE TITLE
can't create password 

### ISSUE THREAD

**Issue by arus08** [busy-technology/BusyDesktopWallet#4]
I can't make a password always doesn't respond

https://user-images.githubusercontent.com/15024465/161832054-2473afc5-cc9c-47ab-88a0-447e9f4139cd.mp4

**Comment by busy-technology** [comment]
Hello,
Busy Testnet has been under DDoS fire 🔫 for the last three hours, and the attack is still ongoing. We have been forced to terminate Busy API to block the attacker. BusyChain is not affected; nothing happened to the network itself. We are pausing testing of the desktop wallet until further notice. We are honoured to be under the fire already on the testnet. That means that Busy is well awaited. Thank you for your feedback! 🚀
Twitter👉 https://bit.ly/3r5lwqu

**Comment by busy-technology** [comment]
Fixed with new release
