### ISSUE TITLE
Desktop Apps

### ISSUE THREAD

**Issue by avenbreaks** [busy-technology/BusyDesktopWallet#5]
`maybe you can make an application for linux base and macos. not all users use windows. thank you`

**Comment by dimasdnt** [comment]
ok

**Comment by busy-technology** [comment]
Hello,
As per our official statement:
"This version is available only for Windows operating system. Once we receive the initial round of feedback and suggestions, we might implement some improvements, and the final version will also be released for the macOS and Linux operating systems."
https://info.busychain.io/busy-desktop-wallet-installation-file/
